#!/bin/bash
# Template post-install hook file to build packages for numigi-ppa
# You might write any instructions you want to execute after the installation of a package here.
set -euo pipefail
echo "Nothing to do here"
exit 1
